### ISSUE TITLE
android-create-project error

### ISSUE THREAD

**Issue by wjain** [remvee/android-mode#43]
I use emacs 24.4 on windows 8.1.
when M-x android-create-project ,I got this error:

Making completion list...
if: Error: Argument 'com.test.hello' is not recognized.

       Usage:
       android [global options] create project [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                         Action "create project":
  Creates a new Android project.
Options:
  -n --name          : Project name.
  -a --activity      : Name of the default Activity that is created.
                       [required]
  -k --package       : Android package name for the application. [required]
  -v --gradle-version: Gradle Android plugin version.
  -t --target        : Target ID of the new project. [required]
  -g --gradle        : Use gradle template.
  -p --path          : The new project's directory. [required]

After I modify  android-create-project:
       ; (command (format "%s create project --path %S --package %s --activity %s --target %S"
==>
         (command (format "%s create project --path %s --package %s --activity %s --target %s"

It work ok。

**Comment by remvee** [comment]
See #45
