### ISSUE TITLE
android-start-app assumes AndroidManifest.xml is in android-root

### ISSUE THREAD

**Issue by wizmer** [remvee/android-mode#51]
I have a project with the following layout:

./gradew
./gradle/
./projectFiles
./MyActualProjectDir/src/main/AndroidManifest.xml

All my gradle commands have to be launched from the root dir so the root dir is set at the top level. This works for building the project.
However when I try to launch it with android-start-app, it is looking for the manifest in the top dir and it does not find it. 

Would it be possible to separate android-root-dir from the place the manifest is ?

Thanks

**Comment by remvee** [comment]
This is related to #50, look at the comment I just made. The `android-root-dir` function needs to be smarter and find `gradew` to find the root and look for `AndroidManifest.xml` to confirm it's an android project.

My knowledge of android app development is ancient so a PR and a link to an android application repository to test with would be very welcome.

**Comment by remvee** [comment]
Ah, I just found this: https://github.com/eunmin/android-mode/commit/e4fc34d01f3520bc725747ce44390e541b468af3.  Does that fix the problem?

**Comment by remvee** [comment]
See #50
